### ISSUE TITLE
sbt-fresh causes failure in non-fresh-built projects.

### ISSUE THREAD

**Issue by aaronlevin** [sbt/sbt-fresh#86]
I used `sbt-fresh` to build a new project. Then I went to work on an older project (`other-project`) that was setup before I installed `sbt-fresh` and received the following error:

```
☭ (master) sbt
[info] Loading global plugins from /home/aaronlevin/.sbt/0.13/plugins
[info] Loading project definition from /home/aaronlevin/dev/other-project/project
java.lang.NoSuchMethodError: de.heikoseeberger.sbtfresh.FreshPlugin$autoImport$.freshSetUpTravis()Lsbt/SettingKey;
	at $b5a672f744a77296b203$.$sbtdef(/home/aaronlevin/.sbt/0.13/build.sbt:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.Eval$.getValue(Eval.scala:464)
	at sbt.compiler.Eval$$anonfun$4.apply(Eval.scala:97)
	at sbt.compiler.Eval$$anonfun$4.apply(Eval.scala:97)
	at sbt.EvaluateConfigurations$$anonfun$evaluateDslEntry$1.apply(EvaluateConfigurations.scala:185)
	at sbt.EvaluateConfigurations$$anonfun$evaluateDslEntry$1.apply(EvaluateConfigurations.scala:183)
	at sbt.EvaluateConfigurations$$anonfun$evaluateSbtFile$1$$anonfun$11.apply(EvaluateConfigurations.scala:128)
	at sbt.EvaluateConfigurations$$anonfun$evaluateSbtFile$1$$anonfun$11.apply(EvaluateConfigurations.scala:128)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.EvaluateConfigurations$$anonfun$evaluateSbtFile$1.apply(EvaluateConfigurations.scala:128)
	at sbt.EvaluateConfigurations$$anonfun$evaluateSbtFile$1.apply(EvaluateConfigurations.scala:122)
	at sbt.EvaluateConfigurations$$anonfun$apply$2$$anonfun$apply$3.apply(EvaluateConfigurations.scala:50)
	at sbt.EvaluateConfigurations$$anonfun$apply$2$$anonfun$apply$3.apply(EvaluateConfigurations.scala:50)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.EvaluateConfigurations$$anonfun$apply$2.apply(EvaluateConfigurations.scala:50)
	at sbt.EvaluateConfigurations$$anonfun$apply$2.apply(EvaluateConfigurations.scala:50)
	at sbt.Load$$anonfun$buildGlobalSettings$1.apply(Load.scala:93)
	at sbt.Load$$anonfun$buildGlobalSettings$1.apply(Load.scala:92)
	at sbt.Load$InjectSettings$$anonfun$cachedProjectLoaded$1.apply(Load.scala:992)
	at sbt.Load$InjectSettings$$anonfun$cachedProjectLoaded$1.apply(Load.scala:992)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at sbt.Load$InjectSettings.cachedProjectLoaded(Load.scala:992)
	at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:735)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:740)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
	at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:742)
	at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:703)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.resolveProject(Load.scala:703)
	at sbt.Load$.sbt$Load$$finalizeProject$1(Load.scala:603)
	at sbt.Load$$anonfun$54.apply(Load.scala:652)
	at sbt.Load$$anonfun$54.apply(Load.scala:652)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:651)
	at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.loadUnit(Load.scala:459)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:365)
	at sbt.Load$.loadURI(Load.scala:320)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.defaultLoad(Load.scala:39)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:496)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:496)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

Here is my installation:

```
☭ (master) cat ~/.sbt/0.13/plugins/plugins.sbt 
resolvers ++= Seq(
    "Sonatype OSS Releases" at "https://oss.sonatype.org/content/repositories/releases/",
      "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
    )

addSbtPlugin("net.ceedubs" %% "sbt-ctags" % "0.2.0")

addSbtPlugin("org.ensime" % "sbt-ensime" % "0.6.0")

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.6.0")

addSbtPlugin("de.heikoseeberger" % "sbt-fresh" % "2.4.4")

addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")

addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "1.1")
```
and
```
☭ (master) cat ~/.sbt/0.13/build.sbt 

import de.heikoseeberger.sbtfresh.FreshPlugin.autoImport._
import de.heikoseeberger.sbtfresh.license.License

freshOrganization := "ca.aaronlevin"        // Organization – "default" by default
freshAuthor       := "Aaron Levin"        // Author – value of "user.name" system property or "default" by default
freshLicense      := Some(License.mit) // Optional license – `apache20` by default
freshSetUpGit     := true              // Initialize a Git repo and create an initial commit – `true` by default
freshSetUpTravis  := true              // Configure Travis for Continuous Integration - `true` by default
freshUseGitPrompt := true              // Use the prompt from the sbt-git plugin - `false` by default
```

any idea what is going on? I would expect `sbt-fresh` to be somewhat isolated and not cause older projects that did not use it to fail. perhaps I've configured something wrong?

**Comment by hseeberger** [comment]
I have no precise idea what's going on. Have you tried to delete all `target` directories in your older project:

```
find . -name target | xargs rm -r
```

Another idea: Maybe your older project is using some old version of sbt, e.g. 0.13.5 or so? What's the content of `project/build.properties`?

**Comment by BranislavLazic** [comment]
Deleting all target directories worked in my case.
